const englishSpeakingCountries = [
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "New Zealand",
    "Ireland",
    "South Africa",
    "Jamaica",
    "Barbados",
    "Trinidad and Tobago",
    "Nigeria",
    "Ghana",
    "Kenya",
    "Uganda",
    "India",
    "Pakistan",
    "Philippines",
    "Singapore",
    "Malta",
    "Fiji",
    "Bahamas",
    "Grenada",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Belize",
    "Guyana",
    "Antigua and Barbuda",
    "Saint Kitts and Nevis",
    "Liberia",
    "Sierra Leone",
    "Zambia",
    "Zimbabwe",
    "Botswana",
    "Namibia",
    "Lesotho"
  ];
  


  const englishLearningPlans = [
    "Beginner English Course",
    "Intermediate English Course",
    "Advanced English Course",
    "Business English Program",
    "English for Travel",
    "IELTS Preparation Course",
    "TOEFL Preparation Course",
    "English Conversation Classes",
    "English Grammar Bootcamp",
    "Academic English Program",
    "English for Specific Purposes (ESP)",
    "English for Kids",
    "English for Teens",
    "English Pronunciation Workshop",
    "English Writing Skills Course",
    "English Reading Comprehension Course",
    "English Listening and Speaking Course",
    "Online English Tutoring",
    "English Language Immersion Program",
    "English Vocabulary Builder",
    "English for Healthcare Professionals",
    "English for IT Professionals",
    "Cambridge English Exam Preparation",
    "TOEIC Preparation Course",
    "English for Customer Service",
    "English for Hospitality and Tourism",
    "Intensive English Program",
    "One-on-One English Coaching",
    "General English Course",
    "English for Academic Purposes (EAP)"
  ];
  

  export default englishSpeakingCountries
  export {englishLearningPlans}